/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.util.Random;
import java.util.regex.*;
import javax.swing.JTextField;

/**
 *
 * @author markr
 */
public class Insert_rec extends javax.swing.JFrame {

    Connection connection;
    Statement st;
    ResultSet rs;

    public final void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/isdb", "root", "1234");
            st = connection.createStatement();

        } catch (ClassNotFoundException | SQLException ex) {

        }
    }

    /**
     * Creates new form Mainframe
     */
    public Insert_rec() {
        initComponents();
        Connect();
        generateUniqueID();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) birthday.getDateEditor();
        editor.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userFirstName = new javax.swing.JTextField();
        userMiddleName = new javax.swing.JTextField();
        userLastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        userAddress = new javax.swing.JTextField();
        jlabel9 = new javax.swing.JLabel();
        userMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        userPass = new javax.swing.JPasswordField();
        userConfirmpass = new javax.swing.JPasswordField();
        exit_button = new javax.swing.JButton();
        ckbox = new javax.swing.JCheckBox();
        birthday = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_label.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        login_label.setForeground(new java.awt.Color(0, 51, 51));
        login_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_label.setText("ADD RECORD");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("ID:");

        userID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userID.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Last Name:");

        userLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLastNameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel11.setText("Address:");

        jlabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlabel9.setText("Mobile No.: 09xxxxxxxxxx (11 digit)");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setText("Confirm Password:");

        add_button.setBackground(new java.awt.Color(0, 51, 51));
        add_button.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setText("ADD RECORD");
        add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button.setFocusPainted(false);
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_buttonMouseExited(evt);
            }
        });
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        userConfirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userConfirmpassActionPerformed(evt);
            }
        });

        exit_button.setBackground(new java.awt.Color(0, 51, 51));
        exit_button.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        exit_button.setForeground(new java.awt.Color(255, 255, 255));
        exit_button.setText("EXIT");
        exit_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setFocusPainted(false);
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_buttonMouseExited(evt);
            }
        });
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        ckbox.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        ckbox.setText("View Password");
        ckbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckboxActionPerformed(evt);
            }
        });

        birthday.setFocusable(false);
        birthday.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Birthday:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Middle Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userID, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(userFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(userMobile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(exit_button, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(birthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userConfirmpass)
                            .addComponent(userEmail)))
                    .addComponent(ckbox))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(login_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userConfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void generateUniqueID() {
        String generatedID;
        do {
            generatedID = generateRandomID();
        } while (isIDInUse(generatedID));

        userID.setText(generatedID);
        userID.setText(generatedID);
    }

    private String generateRandomID() {
        Random random = new Random();
        int randomNumber = 100000 + random.nextInt(900000);
        return String.valueOf(randomNumber);
    }

    private boolean isIDInUse(String id) {
        try {
            PreparedStatement pstmt = connection.prepareStatement("SELECT * FROM reg_tbl WHERE idreg_tbl = '" + id + "'");
            pstmt.setString(1, id);
            rs = pstmt.executeQuery();
            String getID = "";
            if (rs.next()) {
                getID = rs.getString("idreg_tbl");
                return id.equals(getID) == false;
            }
        } catch (SQLException e) {
            // Handle the exception appropriately

        }

        return false;
    }

    public static boolean isValidEmail(String email) {
        String REGEX = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
        Pattern pattern = Pattern.compile(REGEX);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    private boolean passwordChecker(String password) {
        if (password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "password cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //password length
        if (password.length() < 8 || password.length() > 20) {
            JOptionPane.showMessageDialog(null, "password must be between 8 to 20 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!Pattern.compile("[a-z]").matcher(password).find()) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one lower case", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!Pattern.compile("[A-Z]").matcher(password).find()) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one upper case", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!Pattern.compile("[0-9]").matcher(password).find()) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one digit", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!Pattern.compile("[,.;:'|~`/!@#$%&*()_+=|<>?-]").matcher(password).find()) {
            JOptionPane.showMessageDialog(null, "Password must contain at least one symbol", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private boolean confirmPassword(String password) {
        String confirmPass = userPass.getText();
        return confirmPass.equals(password);
    }

    private boolean numChecker(String mobileNumber) {
        String regex = "^\\d{11}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(mobileNumber);
        return matcher.matches();
    }

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        String bd;
        try {
            if (userFirstName.getText().equals("") || userMiddleName.getText().equals("") || userLastName.getText().equals("") || userAddress.getText().equals("") || userMobile.getText().equals("") || userID.getText().equals("") || userPass.getText().equals("") || userConfirmpass.getText().equals("") ||((JTextField) birthday.getDateEditor().getUiComponent()).getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (numChecker(userMobile.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Invalid Mobile number", "Error", JOptionPane.ERROR_MESSAGE);
                userMobile.setText(null);

            } else if (isValidEmail(userEmail.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Invalid email address", "Error", JOptionPane.ERROR_MESSAGE);
                userEmail.setText(null);

            } else if (passwordChecker(userPass.getText()) == false) {
                userPass.setText(null);
                userConfirmpass.setText(null);
            } else if (confirmPassword(userConfirmpass.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Password does not match", "Error", JOptionPane.ERROR_MESSAGE);
                userPass.setText(null);
                userConfirmpass.setText(null);
            } else {
                bd = ((JTextField) birthday.getDateEditor().getUiComponent()).getText();
                st.executeUpdate("Insert into reg_tbl("
                        + "idreg_tbl,firstname,middlename,lastname,address,birthday,mobileno,email,"
                        + "password" + ") VALUES ('"
                        + userID.getText() + "','"
                        + userFirstName.getText() + "','"
                        + userMiddleName.getText() + "','"
                        + userLastName.getText() + "','"
                        + userAddress.getText() + "','"
                        + bd + "','"
                        + userMobile.getText() + "','"
                        + userEmail.getText() + "','"
                        + userPass.getText() + "')");
                JOptionPane.showMessageDialog(null, """
                                                    Record Created
                                                    Record ID:  """ + userID.getText(),
                        "System Message", JOptionPane.INFORMATION_MESSAGE);
                Menu main = new Menu();
                main.setVisible(true);
                dispose();
            }
        } catch (SQLException ex) {
            // Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("nge");
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        Menu main = new Menu();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void ckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckboxActionPerformed
        if (ckbox.isSelected()) {
            userPass.setEchoChar((char) 0);
            userConfirmpass.setEchoChar((char) 0);
        } else {
            userPass.setEchoChar('\u2022');
            userConfirmpass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ckboxActionPerformed

    private void add_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseEntered
        add_button.setBackground(new Color(255, 255, 255));
        add_button.setForeground(new Color(0, 51, 51));
        add_button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_add_buttonMouseEntered

    private void add_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseExited
        add_button.setBackground(new Color(0, 51, 51));
        add_button.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_add_buttonMouseExited

    private void exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseEntered
        exit_button.setBackground(new Color(255, 255, 255));
        exit_button.setForeground(new Color(0, 51, 51));
        exit_button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exit_buttonMouseEntered

    private void exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseExited
        exit_button.setBackground(new Color(0, 51, 51));
        exit_button.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_exit_buttonMouseExited

    private void userConfirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userConfirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userConfirmpassActionPerformed

    private void userLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLastNameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.JCheckBox ckbox;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel login_label;
    private javax.swing.JTextField userAddress;
    private javax.swing.JPasswordField userConfirmpass;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userFirstName;
    private javax.swing.JTextField userID;
    private javax.swing.JTextField userLastName;
    private javax.swing.JTextField userMiddleName;
    private javax.swing.JTextField userMobile;
    private javax.swing.JPasswordField userPass;
    // End of variables declaration//GEN-END:variables
}
